net = input("Please enter network and maks x.x.x.x/y: ")
ip, mask = net.split("/")
octets = ip.split(".")
print("Network:")
print(f"{octets[0]:<8} {octets[1]:<8} {octets[2]:<8} {octets[3]:<8}")
print(f"{int(octets[0]):>08b} {int(octets[1]):>08b} {int(octets[2]):>08b} {int(octets[3]):>08b}")
mask_str = "1" * int(mask) + "0" * (32 - int(mask))
first_oct = int(mask_str[0:8], 2)
second_oct = int(mask_str[8:16], 2)
third_oct = int(mask_str[16:24], 2)
fourth_oct = int(mask_str[24-32], 2)
print("\n/" + mask)
print(f"{first_oct:<8} {second_oct:<8} {third_oct:<8} {fourth_oct:<8}")
print(f"{mask_str[0:8]} {mask_str[8:16]} {mask_str[16:24]} {mask_str[24:32]}")

